### PR TITLE
Added ESP32 support

### PR DESCRIPTION
**Pull request by bart**
Set different SPI pins for ESP32 boards

### CODE REVIEW

**Comment by bart** [comment]
FYI: Added SPI pin mapping for TTGO ESP32 T8 v1.7 board which does not have default ESP32 SPI pins. Maybe we should add a method instead to set SPI pins during init?

Default ESP32 (V)SPI pinout is:

MOSI = 23
MISO = 19
CLK = 18
CS = 5

**Comment by dparson55** [comment]
Thanks for helping to add ESP32 support and the idea to allow configuration of the SPI pins.  I don't have one of these microcontrollers so can you see if the commit I made to your fork works?  I removed the changes you made to `init` and instead added `initEsp32`.

**Comment by bart** [comment]
Wow, thanks for your quick implementation! Really love your library and for sure trying to improve it as good as I can by keeping it as simple as possible, too. Tested it on ESP32 (TTGO brand) using new initEsp32() method and after adding missing semicolon in NRFLite.h it works well. Well done!

**Comment by dparson55** [comment]
Sure thing and I'm grateful for the help and good ideas on keeping the library simple.  I made another change allowing `init` to handle the situation where the SPI library supports configurable pins.  I added a `Basic_RX_ESP32' example.  Does this work ok?

**Comment by bart** [comment]
Works very good sir, thank you so much. Removed TTGO brand name from example because your example pin mapping is for default ESP32 boards (which is better than TTGO). I think it's ready to merge now.

**Comment by dparson55** [comment]
Awesome, thanks again!

**Pull request merged**
