### PR TITLE
Measurement count for scanChannel

### PR DESCRIPTION
**Pull request by Delph**
Doing 255 channels reads takes some time, so I've exposed `measurementCount` as a parameter for `scanChannel` to allow a user to reduce this.

~`setChannel` and `setRadioId` use the same setup as in the `init` function to set those properties.~

### CODE REVIEW

**Comment by dparson55** [comment]
Hi Delph, one of the goals for this library is keeping things simple (the Lite in NRFLite) and `init` already does radio id and channel assignments, so I hesitate to add these additional public methods since it adds complexity for the user.  Why not use `init` when you need to change them?

The addition of the `measurementCount` parameter seems like it would be less impactful so I would be ok with just that change.

**Comment by Delph** [comment]
`scanChannel` changes the channel too though, which then becomes problematic without a `setChannel`.

I have a project where I'm after in the field setup, as each time it'll be used it'll be in a different place and with a different number of radios. It has an inbuilt channel scanner graph and I can set these values by hand. If I can just call `init` again (I wasn't really sure), that's not really a problem, although it seems a little heavy handed.

I don't think these two add much complexity, they do exactly what they say and they don't seem out of scope. I guess the question here is are you after a small library, or a simple library?

**Comment by dparson55** [comment]
Sounds like a very cool project!  If you use `init` for the channel and radio id assignments it will be orders of magnitude slower than changing them directly, but it will work ok.  I am actually thinking your project might have outgrown this more basic library and sticking with your forked version or switching to a more feature-complete library would be better, especially since you are needing such fine grained control (and speed) from the radio.

I really want to limit the number of public methods and only want to give users one way to do things to keep the library as simple to use as possible.  If anything I want to reduce the number of methods and parameters that users need to consider.

So I would be ok with this PR if you only include the `measurementCount` change.

**Comment by Delph** [comment]
Okay. I've dropped the second commit, calling `init` again will work for my purposes and it isn't a performance concern (this is all for configuration stuff, not actual run time stuff). Doing 255 reads of 125 channels and displaying them on an lcd was a bit slow, but for the purposes of telling if a channel is simply busy, 50 reads is plenty.

Out of interest, are you familiar with any libraries for AVR other than this and [RF24](https://github.com/nRF24/RF24)?

**Comment by dparson55** [comment]
I created a 3.0.1 release for this PR and it's now available.

Besides RF24, there are also the MySensors, RadioHead, and Mirf libraries.
https://playground.arduino.cc/InterfacingWithHardware/Nrf24L01/

Best wishes and thanks again!

**Pull request merged**
